services:
   #eureka-server:
   #  image: eureka:latest
   #  container_name: eureka-server
   #  ports:
   #    - "8761:8761"
   #  env_file:
   #    - eureka/eureka.env

  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - api-gateway/api-gateway.env
  #   depends_on:
  #     - db-gateway
  #     - eureka-server

  # product-service:
  #   build: ./product-service
  #   ports:
  #     - "8083:8080"
  #   env_file:
  #     - product-service/product.env
  #   depends_on:
  #     - db-product
  #     - redis
  #     - eureka-server

  # user-service:
  #   build: ./user-service
  #   ports:
  #     - "8081:8080"
  #   env_file:
  #     - user-service/user.env
  #   depends_on:
  #     - db-user
  #     - redis
  #     - eureka-server

  # order-service:
  #   build: ./order-service
  #   ports:
  #     - "8082:8080"
  #   env_file:
  #     - order-service/order.env
  #   depends_on:
  #     - db-order
  #     - redis
  #     - eureka-server

  # db-gateway:
  #   image: postgres:latest
  #   container_name: db-gateway
  #   env_file:
  #     - api-gateway/db.env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/db-gateway:/var/lib/postgresql/data

  db-user:
    image: postgres:latest
    container_name: db-user
    env_file:
      - user-service/db.env
    ports:
      - 5433:5432
    volumes:
      - ./data/db-user:/var/lib/postgresql/data

  db-order:
    image: postgres:latest
    container_name: db-order
    env_file:
      - order-service/db.env
    ports:
      - 5434:5432
    volumes:
      - ./data/db-order:/var/lib/postgresql/data

  db-product:
    image: postgres:latest
    container_name: db-product
    env_file:
      - product-service/db.env
    ports:
      - 5435:5432
    volumes:
      - ./data/db-product:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: db-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: Yu7Zm8XeT7m9kCnrMsDH1Q
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    volumes:
      - ./kafka-data:/var/lib/kafka/data